name: Generate EPG every day
on:
  schedule:
    - cron: '00 00-16/4 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: config
        run: |
          git pull
          git config --global user.email "reinmclaren33@gmail.com"
          git config --global user.name "Faizal Hamzah"
      - name: generate
        run: |
          cd epg/scripts
          pwd
          echo "Installing dependencies..."
          python3 -m pip install lxml pgzip requests
          echo "Generating EPG..."
          python3 -u index.py -zo guide.xml --source="global/global.txt" --gen-name="Libretelevision" --gen-url="libretv.my.id"
          mv -v guide.xml.gz ..
          cd ../..
      - name: commit
        run: |
          git add -A
          git commit -m "Generate EPG every day"
          git push
